### PR TITLE
Renaming FutureListener to Completable

### PR DESCRIPTION
**Pull request by david-at-aws**
The more I play with it, the more "FutureListener" rubs me the wrong way. It sounds too much like its something I should be implementing and passing to a Future to listen for completions, rather than a way for me to complete a future that someone else is listening to.

How do you feel about ```Completable```? A bit close to Java 8's CompletableFuture, but this is basically a subset of that which should go away once we drop support for 7. Seems to capture the intent a bit better.

(side note: interesting that there's no similar interface for CompletableFuture - you have to deal with a CompletableFuture directly if you want to complete it)

### CODE REVIEW

**Comment by hansonchar** [comment]
My knee jerk response would be to avoid Completable since it draws unnecessary attention and confusion to the CompletableFuture in Java 8.

How about FutureToComplete ?

**Comment by david-at-aws** [comment]
This isn't exposed to users of the API, so I'm less concerned about name collisions than I am about giving it a name that makes sense to us. Speaking of which, moving these two to the internal package. With AsyncTask the only thing left in the async package, maybe that should just move up to the top level?

I don't like FutureToComplete: it sounds like a variable of type Future, not an interface to be able to complete a Future. I could be talked into ResultAcceptor, but think it sounds a bit awkward. Other thoughts?

**Comment by hansonchar** [comment]
This is not an interface - it's not meant to be.  Rather, it's just a side product when we try to make sense of the additional methods of AsyncTaskFuture which has this bunch of additional callback and setter methods.  

Hence my reluctance to give it a general name or interface.  I'd much prefer a specific/local impl name that doesn't (mis-)lead the reader into thinking (or worse using) it more than what it should be.

**Comment by hansonchar** [comment]
Perhaps just give it a humble impl name, like AsyncTaskFutureBase ?  The name doesn't convey much info except it's the base class of AsyncTaskFuture.  The rest, use javadoc to explain the impl details?

**Comment by hansonchar** [comment]
Since we cannot come up with a good name, perhaps this is the sign that we should get rid of this class, and simply merge these additional methods back to AsyncTaskFuture?

**Comment by david-at-aws** [comment]
Agreed on CompletableSpi offline.

**Pull request merged**
