### PR TITLE
add convenient script for switching to Java 7 on mac

### PR DESCRIPTION
**Pull request by hansonchar**

### CODE REVIEW

**Comment by david-at-aws** [comment]
Having Java 7 installed/configured via JAVA_HOME is explicitly not a requirement for building this; I for one am not planning on having 7 installed after it's EOL'd in April. :)

Ideally we should hook up travis to automatically build/test with both 7 and 8 (and 9?) to make sure they all work, and let developers build locally using whatever they've got installed.

**Comment by hansonchar** [comment]
For now, don't you need Java 7 to have this built?  This is just a script for convenience, not something you have to execute.  Without this script, you'd still need to manually switch to Java 7.  No?

**Comment by david-at-aws** [comment]
Nope, compiles just fine with 8 again after [this fix](https://github.com/david-at-aws/aws-java-sdk-core/commit/b516da82d96ea39b2615d09d5b4728e85c4e123a).

**Comment by hansonchar** [comment]
Strange. With the latest tip from master, I did "mvn verify" using Java 8, but still got:

>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default->compile) on project aws-java-sdk-core: Fatal error compiling: invalid target release: 1.7 -> [Help 1]

% java -version

>java version "1.8.0_31"
>Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
>Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by david-at-aws** [comment]
Java 8 definitely knows how to compile code to target Java 7. The error you're seeing means that maven is picking up an older JDK (presumably 6?) that doesn't know how to produce code targeting 7. What version of Java does ```mvn -version``` tell you? [Sounds like](http://stackoverflow.com/questions/14043042/compiling-java-7-code-via-maven) some versions of maven on OS X have related issues.

**Comment by hansonchar** [comment]
OK, I'll revert the changes, and simply add the convenient script to my login shell profile.

BTW, I've found a neat way to discard previous commits and sync up with the upstream.  The trick is to first discard previous commits locally via git reset --hard, up to a point where it is in sync with the upstream.  Then force the push to the origin, like so:

>git push --force origin master

**Pull request closed without merging**
